### ISSUE TITLE
导入框架没有效果

### ISSUE THREAD

**Issue by changwuguo** [Bupterambition/MGJPFIntroguideView#3]
你好,按照Demo中的代码去设置,显示不出来效果,是怎么回事?还有就是Demo运行不起来.报错

**Comment by Bupterambition** [comment]
@iOSCountry please run below command in the *.xcworkspace document : pod update --verbose |find *.xcworkspace -depth 0 | xargs open

**Comment by changwuguo** [comment]
![image](https://cloud.githubusercontent.com/assets/17453419/23331731/d7561b22-fba6-11e6-9670-295d376cac42.png)
![image](https://cloud.githubusercontent.com/assets/17453419/23331741/08a8c86e-fba7-11e6-9848-4dc9c48e51db.png)
你好,我感觉这2个地方写的不对.第一个判断条件有误,第二个当下图中的url有值时,就会直接cleanup了
![image](https://cloud.githubusercontent.com/assets/17453419/23331756/4f81c344-fba7-11e6-94c7-210ab77543f2.png)

**Comment by Bupterambition** [comment]
@iOSCountry 可能你没太理解，这么做的原因是因为 图片下载是需要时间的，因此当进入需要展示的界面时，如果不能快速下载图片的话，用户可能就退出界面了，此时如果再展示的话就会发生错误。因此当取不到资源时，就需要清除，当取到资源时，下次进入后通过url这个key就可以获取到资源图了。

**Comment by changwuguo** [comment]
ok, Thanks,但是第一个判断条件,是不是有问题?

**Comment by Bupterambition** [comment]
第一个条件是没有问题的，这因为viewdidlayoutsubviews会被多次调用，因此需要加一个限制判定。当然这个只是我demo中的场景，还需要针对不同业务场景自己来写，如果有问题的话。请私信邮箱bupterambition@gmial.com @iOSCountry

**Comment by changwuguo** [comment]
OK, Thanks!
