### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by idozhuoyong** [Bupterambition/MGJPFIntroguideView#4]
1. isNeedShow方法可能缺少对self.coachMarks的判断
- (BOOL)isNeedShow {
    return !Awesome_IS_EMPTY(self.guideImageItems)||!Awesome_IS_EMPTY(self.descptionItems)||!Awesome_IS_EMPTY(self.masksItems) || !Awesome_IS_EMPTY(self.coachMarks);
}

2.goToCoachMarkIndexed方法中 shape 转换应该有误，shapeMap[currentShape] 是对象，shape是枚举类型，所以个人认为不能直接 shape = shapeMap[currentShape]，需要转换
if ([[markDef allKeys] containsObject:@"shape"]) {
            NSString *currentShape = [markDef objectForKey:@"shape"];
            if ([[shapeMap allKeys] containsObject:currentShape]) {
                shape = [shapeMap[currentShape] intValue];
            }
        }

**Comment by Bupterambition** [comment]
好的，十分感谢，第一个可能不需要再加一个判断，因为全屏场景用到；第二个写的时候确实不规范了，谢谢指正。 @idozhuoyong
